### ISSUE TITLE
How can I set template engine from file format?

### ISSUE THREAD

**Issue by OEvgeny** [timrwood/gulp-consolidate#5]
The benefit of consolidate is opportunity not to worry about template languages.
For example I have a gulp task:
```
  gulp.src('./layouts/*.*')
    .pipe(consolidate(???, data))
    .pipe(extRename('html'))
    .pipe(gulp.dest(...))
```
How can I set template engine from file format?

**Comment by sbussard** [comment]
Create an object to map file extension to language. Depending on how involved you want to get you might consider using `gulp-tap`.

Are you wanting to use multiple template languages in the same task in the same project? That raises a red flag to me

**Comment by sbussard** [comment]
Unless you're looking to create a consumable project, then it may be pretty nifty :)

**Comment by OEvgeny** [comment]
No I don't use multiple languages on the same project. Seems it was about markdown and jade.

I think we can close it now.
